--------------------------------------------------------
--  파일이 생성됨 - 토요일-5월-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "YSE"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 137 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOK
--------------------------------------------------------

   CREATE SEQUENCE  "YSE"."SEQ_BOOK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FREE
--------------------------------------------------------

   CREATE SEQUENCE  "YSE"."SEQ_FREE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER
--------------------------------------------------------

   CREATE SEQUENCE  "YSE"."SEQ_MEMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTICE
--------------------------------------------------------

   CREATE SEQUENCE  "YSE"."SEQ_NOTICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "YSE"."BOARD" 
   (	"BONO" NUMBER(8,0), 
	"BOTITLE" VARCHAR2(400 BYTE), 
	"BOCONTENT" VARCHAR2(4000 BYTE), 
	"BOWRITER" VARCHAR2(150 BYTE), 
	"BODATE" DATE, 
	"BOHIT" NUMBER(8,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "YSE"."BOARD"  IS '일반게시판';
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "YSE"."BOOK" 
   (	"BOOK_ID" NUMBER(8,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CATEGORY" VARCHAR2(200 BYTE) DEFAULT '', 
	"PRICE" NUMBER(10,0) DEFAULT 0, 
	"INSERT_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "YSE"."BOOK"."BOOK_ID" IS '책아이디';
   COMMENT ON COLUMN "YSE"."BOOK"."CATEGORY" IS '책카테고리';
   COMMENT ON COLUMN "YSE"."BOOK"."PRICE" IS '책가격';
   COMMENT ON COLUMN "YSE"."BOOK"."INSERT_DATE" IS '책등록일';
   COMMENT ON TABLE "YSE"."BOOK"  IS '책';
--------------------------------------------------------
--  DDL for Table FREE
--------------------------------------------------------

  CREATE TABLE "YSE"."FREE" 
   (	"BONO" NUMBER(8,0), 
	"BOTITLE" VARCHAR2(400 BYTE), 
	"BOCONTENT" VARCHAR2(4000 BYTE), 
	"BOWRITER" VARCHAR2(150 BYTE), 
	"BODATE" DATE, 
	"BOHIT" NUMBER(8,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "YSE"."FREE"  IS '일반게시판';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "YSE"."MEMBER" 
   (	"MEM_NO" NUMBER(8,0), 
	"MEM_ID" VARCHAR2(100 BYTE), 
	"MEM_PW" VARCHAR2(100 BYTE), 
	"MEM_NAME" VARCHAR2(100 BYTE), 
	"MEM_GENDER" VARCHAR2(12 BYTE), 
	"MEM_PHONE" VARCHAR2(60 BYTE), 
	"MEM_EMAIL" VARCHAR2(200 BYTE), 
	"MEM_AGREE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "YSE"."NOTICE" 
   (	"BONO" NUMBER(8,0), 
	"BOTITLE" VARCHAR2(400 BYTE), 
	"BOCONTENT" VARCHAR2(4000 BYTE), 
	"BOWRITER" VARCHAR2(150 BYTE), 
	"BODATE" DATE, 
	"BOHIT" NUMBER(8,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "YSE"."NOTICE"  IS '일반게시판';
REM INSERTING into YSE.BOARD
SET DEFINE OFF;
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (1,'제발 등록되어라 제목임','<div class="youtube-embed-wrapper" style="position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden"><iframe allowfullscreen="" frameborder="0" height="0" src="https://www.youtube.com/embed/S8KvwY2tqas" style="position:absolute;top:0;left:0;width:100%;height:100%" width="0"></iframe></div>

<p>등록되어라 내용이다다다닫</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),1);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (2,'제발 등록되어라 제목임2','<p>이번은 두번째임</p>

<div class="youtube-embed-wrapper" style="position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden"><iframe allowfullscreen="" frameborder="0" height="0" src="https://www.youtube.com/embed/AvJ0aphXwM0" style="position:absolute;top:0;left:0;width:100%;height:100%" width="0"></iframe></div>

<p>하하하 이건 키보드</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),2);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (3,'234','<p>234</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),8);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (4,'888','<p>888</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),12);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (15,'제목1','내용1','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (6,'234ㄴㅇㄹ','<p>등록!!!!!!</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),6);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (7,'234ㄴㅇㄹ','<p>등록!!!!!!- 수정</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),1);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (8,'이이이잉것','<p>sㅇㄹㄴㅇㄹㅇㄴㄹㅇㄴㄹ</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),2);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (16,'제목2','내용2','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (10,'제발 등록되어라 제목임2-ㅜㅜㅜㅜ','<p>이게 뭐가 뭔지....</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),2);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (11,'최종입니다다다다ㅏ다다닫','<div class="youtube-embed-wrapper" style="position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden"><object height="0" style="position:absolute;top:0;left:0;width:100%;height:100%" width="0"><param name="movie" value="https://www.youtube.com/v/a_N8PyYTTRA?hl=en&amp;version=3" /><param name="allowFullScreen" value="true" /><param name="allowscriptaccess" value="always" /><embed allowfullscreen="true" allowscriptaccess="always" height="0" src="https://www.youtube.com/v/a_N8PyYTTRA?hl=en&amp;version=3" style="position:absolute;top:0;left:0;width:100%;height:100%" type="application/x-shockwave-flash" width="0" /></object></div>

<p>희ㅡ히- 수정했어용ㅇㅊㅇㅇㅇㅇ</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),6);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (14,'정렬 잘 됨','<p>하하ㅏ하</p>

<p>하하</p>

<p>하</p>

<p>하하</p>

<p>하하하-수정</p>
','a001',to_date('2023/05/18','YYYY/MM/DD'),12);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (17,'제목3','내용3','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (18,'제목21','내용21','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (19,'제목3','내용3','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (20,'제목4','내용4','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (21,'제목5','내용5','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (22,'제목6','내용6','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (23,'제목7','내용7','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (24,'제목8','내용8','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (25,'제목9','내용9','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (26,'제목10','내용10','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (27,'제목11','내용11','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (28,'제목12','내용12','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (29,'제목13','내용13','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (30,'제목14','내용14','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (31,'제목15','내용15','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (32,'제목16','내용16','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (33,'제목17','내용17','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (34,'제목18','내용18','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (35,'제목19','내용19','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (36,'제목20','내용20','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (37,'제목21','내용21','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (38,'제목22','내용22','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (39,'제목23','내용23','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (40,'제목24','내용24','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (41,'제목25','내용25','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (42,'제목26','내용26','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (43,'제목27','내용27','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (44,'제목28','내용28','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (45,'제목29','내용29','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (46,'제목30','내용30','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (47,'제목31','내용31','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (48,'제목32','내용32','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (49,'제목33','내용33','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (50,'제목34','내용34','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (51,'제목35','내용35','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (52,'제목36','내용36','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (53,'제목37','내용37','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (54,'제목38','내용38','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (55,'제목39','내용39','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (56,'제목40','내용40','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (57,'제목41','내용41','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (58,'제목42','내용42','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (59,'제목43','내용43','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (60,'제목44','내용44','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (61,'제목45','내용45','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (62,'제목46','내용46','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (63,'제목47','내용47','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (64,'제목48','내용48','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (65,'제목49','내용49','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (66,'제목50','내용50','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (67,'제목51','내용51','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (68,'제목52','내용52','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (69,'제목53','내용53','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (70,'제목54','내용54','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (71,'제목55','내용55','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (72,'제목56','내용56','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (73,'제목57','내용57','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (74,'제목58','내용58','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (75,'제목59','내용59','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (76,'제목60','내용60','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (77,'제목61','내용61','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (78,'제목62','내용62','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (79,'제목63','내용63','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (80,'제목64','내용64','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (81,'제목65','내용65','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (82,'제목66','내용66','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (83,'제목67','내용67','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (84,'제목68','내용68','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (85,'제목69','내용69','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (86,'제목70','내용70','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (87,'제목71','내용71','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (88,'제목72','내용72','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (89,'제목73','내용73','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (90,'제목74','내용74','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (91,'제목75','내용75','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (92,'제목76','내용76','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (93,'제목77','내용77','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (94,'제목78','내용78','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (95,'제목79','내용79','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (96,'제목80','내용80','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (97,'제목81','내용81','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (98,'제목82','내용82','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (99,'제목83','내용83','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (100,'제목84','내용84','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (101,'제목85','내용85','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (102,'제목86','내용86','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (103,'제목87','내용87','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (104,'제목88','내용88','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (105,'제목89','내용89','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (106,'제목90','내용90','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (107,'제목91','내용91','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (108,'제목92','내용92','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (109,'제목93','내용93','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (110,'제목94','내용94','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (111,'제목95','내용95','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (112,'제목96','내용96','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (113,'제목97','내용97','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (114,'제목98','내용98','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (115,'제목99','내용99','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (116,'제목100','내용100','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (117,'제목101','내용101','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (118,'제목102','내용102','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (119,'제목103','내용103','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (120,'제목104','내용104','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (121,'제목105','내용105','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (122,'제목106','내용106','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (123,'제목107','내용107','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (124,'제목108','내용108','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (125,'제목109','내용109','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (126,'제목110','내용110','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (127,'제목111','내용111','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (128,'제목112','내용112','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (129,'제목113','내용113','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (130,'제목114','내용114','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (131,'제목115','내용115','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (132,'제목116','내용116','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (133,'제목117','내용117','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (134,'제목118','내용118','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (135,'제목119','내용119','a001',to_date('2023/05/18','YYYY/MM/DD'),0);
Insert into YSE.BOARD (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (136,'테스트 하는중','<p>테스트 내용임 ㅎㅎㅎㅇ</p>
','a001',to_date('2023/05/19','YYYY/MM/DD'),8);
REM INSERTING into YSE.BOOK
SET DEFINE OFF;
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (1,'독수리처럼 탈주하기','동물',10000,to_date('2023/05/16','YYYY/MM/DD'));
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (2,'동그라미','동화',10000000,to_date('2023/05/17','YYYY/MM/DD'));
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (9,'자바','java',100000,to_date('2023/05/17','YYYY/MM/DD'));
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (4,'가나초퀄릿','디저트',100000,to_date('2023/05/17','YYYY/MM/DD'));
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (10,'가야','삼국지',100030,to_date('2023/05/17','YYYY/MM/DD'));
Insert into YSE.BOOK (BOOK_ID,TITLE,CATEGORY,PRICE,INSERT_DATE) values (8,'오늘 점심은','햄버거',1000,to_date('2023/05/17','YYYY/MM/DD'));
REM INSERTING into YSE.FREE
SET DEFINE OFF;
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (2,'ㅇㄹㅇㅀ','ㄴㅇㄹㄴㅇ
ㄴㅇㄹㄴㅇㄹ
ㄹㅇㄴㄹㄴㅇㄹ','a001',to_date('2023/05/19','YYYY/MM/DD'),8);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (3,'테스트 수정','ㅇㅂㅂ
ㄹㄹ

ㄹㄹ','a001',to_date('2023/05/19','YYYY/MM/DD'),0);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (4,'테스트 수정','ㅇㅂㅂ
ㄹㄹ

ㄹㄹ','a001',to_date('2023/05/19','YYYY/MM/DD'),3);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (5,'테스트 수정 2','ㅣㅇㄴ라ㅓ나일ㅇ
ㄴㄹㄴㅇ
ㄹ
ㅇㄴㄹ','a001',to_date('2023/05/19','YYYY/MM/DD'),10);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (6,'테스트 수정 2','수정합니도','a001',to_date('2023/05/19','YYYY/MM/DD'),7);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (7,'ㄴㄹㅇㄴ','ㄴㅇㄹ','a001',to_date('2023/05/19','YYYY/MM/DD'),7);
Insert into YSE.FREE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (9,'sdf','<p>sdf</p>
','a001',to_date('2023/05/19','YYYY/MM/DD'),1);
REM INSERTING into YSE.MEMBER
SET DEFINE OFF;
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (3,'eunji','1234','홍길동','M','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (4,'eunji3','1234','홍길동','M','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (5,'eunji4','1234','홍길동','M','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (6,'eunji5','1234','홍길동','M','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (7,'eunji6','1234','홍길동','M','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (8,'eunji7','1234','김길순','F','01000001111','aaa@nnn.com','on');
Insert into YSE.MEMBER (MEM_NO,MEM_ID,MEM_PW,MEM_NAME,MEM_GENDER,MEM_PHONE,MEM_EMAIL,MEM_AGREE) values (9,'eunji@naver.com','1234','김길순','F','01000002222','aaa@nnn.com','on');
REM INSERTING into YSE.NOTICE
SET DEFINE OFF;
Insert into YSE.NOTICE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (1,'제목','<p>ㅇ</p>

<p>ㅇㅇ</p>

<p>ㅇ</p>

<p>ㅇ</p>

<p>ㅇ</p>

<p>ㅇ</p>

<p>&nbsp;</p>
','a001',to_date('2023/05/19','YYYY/MM/DD'),4);
Insert into YSE.NOTICE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (3,'ㅎㅇㅀ-수정','<p>ㄴㅇㄹㅣㄴㅇ러ㅣㄴㅇ란아ㅓㄹ</p>

<p>ㄴㅇ</p>

<p>ㄴㄹㅇ</p>

<p>ㅇㅁㄴㅇㅁㄴㅇ</p>
','a001',to_date('2023/05/19','YYYY/MM/DD'),25);
Insert into YSE.NOTICE (BONO,BOTITLE,BOCONTENT,BOWRITER,BODATE,BOHIT) values (5,'ㄴㅇㄹ','<p>제발!!!!!!!!!!!!!!!<br />
1</p>

<p>1</p>

<p>1<br />
!<br />
!<br />
!<br />
&nbsp;</p>
','a001',to_date('2023/05/19','YYYY/MM/DD'),2);
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "YSE"."PK_BOARD" ON "YSE"."BOARD" ("BONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YSE"."PK_BOOK" ON "YSE"."BOOK" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_FREE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YSE"."PK_FREE" ON "YSE"."FREE" ("BONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "YSE"."PK_MEMBER" ON "YSE"."MEMBER" ("MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YSE"."PK_NOTICE" ON "YSE"."NOTICE" ("BONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "YSE"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YSE"."BOARD" MODIFY ("BODATE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."BOARD" MODIFY ("BOWRITER" NOT NULL ENABLE);
  ALTER TABLE "YSE"."BOARD" MODIFY ("BOCONTENT" NOT NULL ENABLE);
  ALTER TABLE "YSE"."BOARD" MODIFY ("BOTITLE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."BOARD" MODIFY ("BONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "YSE"."BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YSE"."BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."BOOK" MODIFY ("BOOK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE
--------------------------------------------------------

  ALTER TABLE "YSE"."FREE" ADD CONSTRAINT "PK_FREE" PRIMARY KEY ("BONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YSE"."FREE" MODIFY ("BODATE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."FREE" MODIFY ("BOWRITER" NOT NULL ENABLE);
  ALTER TABLE "YSE"."FREE" MODIFY ("BOCONTENT" NOT NULL ENABLE);
  ALTER TABLE "YSE"."FREE" MODIFY ("BOTITLE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."FREE" MODIFY ("BONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "YSE"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_AGREE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_PHONE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_GENDER" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_PW" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
  ALTER TABLE "YSE"."MEMBER" MODIFY ("MEM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "YSE"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("BONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YSE"."NOTICE" MODIFY ("BODATE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."NOTICE" MODIFY ("BOWRITER" NOT NULL ENABLE);
  ALTER TABLE "YSE"."NOTICE" MODIFY ("BOCONTENT" NOT NULL ENABLE);
  ALTER TABLE "YSE"."NOTICE" MODIFY ("BOTITLE" NOT NULL ENABLE);
  ALTER TABLE "YSE"."NOTICE" MODIFY ("BONO" NOT NULL ENABLE);
